version: '3.5'

services:
  node:
    container_name: school_frontend
    image: node:12
    ports:
      - '3000:3000'
    volumes:
      - ./:/srv/frontend
    working_dir: /srv/frontend
    command: 'npm start'
