version: '3.5'
services:
  api:
    container_name: school_api
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/api
      - /home/api/node_modules
    environment:
      DB_HOST: database
      DB_PORT: 5432

  database:
    container_name: school_db
    image: postgres:13
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432